import type { Redis } from "ioredis";

export interface StreamMessage {
  id: string;
  fields: Record<string, string>;
}

export interface PendingEntry {
  id: string;
  /** The consumer that currently owns the entry. */
  consumer: string;
  /** Milliseconds since the entry was last delivered. */
  idleMs: number;
  /** How many times the entry was delivered (a claim counts as a delivery). */
  deliveryCount: number;
}

export interface ClaimResult {
  /** Entries this call took over, with their fields. */
  messages: StreamMessage[];
  /** Ids that were in the pending list but no longer exist in the stream (Redis 7.0+). */
  deletedIds: string[];
}

export interface StreamQueueOptions {
  /** Connection for normal commands (XADD, XACK, XAUTOCLAIM, XPENDING, XGROUP). */
  redis: Redis;
  /** A connection used ONLY for XREADGROUP ... BLOCK: a blocked connection cannot serve other commands. */
  blocking: Redis;
  /** Key of the stream. */
  stream: string;
  /** How long consume waits for a new entry, in milliseconds. Default 1000. */
  blockMs?: number;
}

/** XAUTOCLAIM scans and claims at most this many entries per call. It is the server default. */
const CLAIM_PAGE = 100;

/**
 * A work queue on one Redis Stream with consumer groups.
 *
 * publish: XADD stream * field value ...
 * consume: XREADGROUP GROUP g c COUNT n BLOCK ms STREAMS stream >   (entries never delivered to the group)
 * ack:     XACK stream g id                                          (removes the id from the pending list)
 * claimStale: XAUTOCLAIM, take over entries another consumer left pending for too long.
 *
 * Delivery is at-least-once: an entry stays in the group's pending list (PEL) until it is acked.
 */
export class StreamQueue {
  private readonly redis: Redis;
  private readonly blocking: Redis;
  private readonly stream: string;
  private readonly blockMs: number;

  constructor(options: StreamQueueOptions) {
    this.redis = options.redis;
    this.blocking = options.blocking;
    this.stream = options.stream;
    this.blockMs = options.blockMs ?? 1000;
  }

  /** Append an entry and resolve with its id (`<ms>-<seq>`, generated by the server). */
  async publish(fields: Record<string, string>): Promise<string> {
    const args = Object.entries(fields).flat();
    const id = await this.redis.xadd(this.stream, "*", ...args);
    if (id === null) throw new Error("XADD returned no id");
    return id;
  }

  /**
   * XGROUP CREATE ... MKSTREAM: create the group (and the stream when missing). `startId` "0"
   * (default) makes the group see the whole stream, "$" only entries added from now on.
   * Idempotent: a BUSYGROUP error (the group exists) is swallowed, every other error is thrown.
   */
  async createGroup(group: string, startId = "0"): Promise<void> {
    try {
      await this.redis.xgroup("CREATE", this.stream, group, startId, "MKSTREAM");
    } catch (error) {
      if (!(error instanceof Error && error.message.startsWith("BUSYGROUP"))) throw error;
    }
  }

  /**
   * Read up to `count` entries never delivered to this group, blocking up to the block time.
   * They enter the pending list of `consumer`. Resolves [] when nothing arrived (the reply is nil).
   * ioredis 6.0.0 on RESP3 returns [[stream, [[id, [field, value, ...]]]]] (or null).
   */
  async consume(group: string, consumer: string, count: number): Promise<StreamMessage[]> {
    const reply = (await this.blocking.xreadgroup(
      "GROUP",
      group,
      consumer,
      "COUNT",
      count,
      "BLOCK",
      this.blockMs,
      "STREAMS",
      this.stream,
      ">",
    )) as [string, [string, string[]][]][] | null;
    if (reply === null) return [];
    return reply.flatMap(([, entries]) => entries.map(toMessage));
  }

  /** XACK: resolve with how many ids were removed from the pending list (0 if already acked). */
  ack(group: string, id: string): Promise<number> {
    return this.redis.xack(this.stream, group, id);
  }

  /**
   * Take over every entry of the group that has been pending for longer than `minIdleMs`, whoever
   * owns it, and make `consumer` the owner. Follows the XAUTOCLAIM cursor until it returns 0-0.
   * Claiming resets the idle time and adds one to the delivery count.
   * Resolves { messages: [], deletedIds: [] } when nothing qualifies.
   *
   * ioredis 6.0.0 returns the full 3 element reply: [next cursor, entries, deleted ids].
   */
  async claimStale(group: string, consumer: string, minIdleMs: number): Promise<ClaimResult> {
    const result: ClaimResult = { messages: [], deletedIds: [] };
    let cursor = "0-0";
    do {
      const [next, entries, deleted] = (await this.redis.xautoclaim(
        this.stream,
        group,
        consumer,
        minIdleMs,
        cursor,
        "COUNT",
        CLAIM_PAGE,
      )) as [string, [string, string[] | null][], string[] | undefined];
      result.messages.push(...entries.filter(hasFields).map(toMessage));
      result.deletedIds.push(...(deleted ?? []));
      cursor = next;
    } while (cursor !== "0-0");
    return result;
  }

  /** Number of entries in the pending list of the group (XPENDING summary form). */
  async pendingCount(group: string): Promise<number> {
    // Reply: [count, smallest id, greatest id, [[consumer, "count"], ...]], and [0, null, null, null] when empty.
    const summary = (await this.redis.xpending(this.stream, group)) as [number, ...unknown[]];
    return summary[0];
  }

  /** The pending list of the group, oldest first (XPENDING extended form). */
  async pendingEntries(group: string, count = 1000): Promise<PendingEntry[]> {
    // Reply: [[id, consumer, idle ms, delivery count], ...]
    const rows = (await this.redis.xpending(this.stream, group, "-", "+", count)) as [
      string,
      string,
      number,
      number,
    ][];
    return rows.map(([id, consumer, idleMs, deliveryCount]) => ({
      id,
      consumer,
      idleMs,
      deliveryCount,
    }));
  }
}

function toMessage([id, flat]: [string, string[] | null]): StreamMessage {
  const fields: Record<string, string> = {};
  const list = flat ?? [];
  for (let i = 0; i + 1 < list.length; i += 2) fields[list[i] as string] = list[i + 1] as string;
  return { id, fields };
}

function hasFields(entry: [string, string[] | null]): entry is [string, string[]] {
  return entry[1] !== null;
}
